services:
  trainer:
    container_name: trainer
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./data:/data"
      - "./models:/models"

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: mehr_minioadmin
      MINIO_ROOT_PASSWORD: 25024_minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data:

